# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeBook
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework'
  pod 'Cosmos', '~> 15.0'

end
